services:
  - type: web
    name: rehui-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_render.sh
    plan: free
    branch: main
    autoDeploy: true
